import {
  Tenant, User, Category, MenuItem, Order, Table,
  InventoryItem, Supplier, AttendanceRecord, SubscriptionPlanConfig
} from './types'

export const SUBSCRIPTION_PLANS: SubscriptionPlanConfig[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 99,
    currency: 'USD',
    interval: 'month',
    features: ['Up to 3 users', '1 POS terminal', 'Basic reports', 'QR Menu', 'Email support'],
    maxUsers: 3,
    maxTables: 10,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 249,
    currency: 'USD',
    interval: 'month',
    features: ['Up to 15 users', '5 POS terminals', 'Advanced analytics', 'KDS integration', 'ZATCA/FTA compliance', 'HR & Payroll', 'Priority support'],
    maxUsers: 15,
    maxTables: 50,
    isPopular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 599,
    currency: 'USD',
    interval: 'month',
    features: ['Unlimited users', 'Unlimited terminals', 'Multi-branch', 'API access', 'Custom integrations', 'Dedicated account manager', '24/7 support'],
    maxUsers: 9999,
    maxTables: 9999,
  },
]

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 't1',
    name: 'Al Fanar Restaurant',
    slug: 'al-fanar',
    countryCode: 'KSA',
    currency: 'SAR',
    vatRate: 0.15,
    vatNumber: '300012345600003',
    address: 'King Fahd Road, Riyadh, KSA',
    phone: '+966-11-123-4567',
    email: 'info@alfanar.com',
    subscriptionPlan: 'enterprise',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    invoiceFooter: 'Thank you for dining with us!',
    primaryColor: '#059669',
  },
  {
    id: 't2',
    name: 'Burj Bites',
    slug: 'burj-bites',
    countryCode: 'UAE',
    currency: 'AED',
    vatRate: 0.05,
    vatNumber: '100987654300003',
    address: 'Downtown Dubai, UAE',
    phone: '+971-4-987-6543',
    email: 'hello@burjbites.ae',
    subscriptionPlan: 'professional',
    isActive: true,
    createdAt: new Date('2023-03-20'),
    invoiceFooter: 'We hope to see you again soon!',
    primaryColor: '#d97706',
  },
  {
    id: 't3',
    name: 'Najd Village',
    slug: 'najd-village',
    countryCode: 'KSA',
    currency: 'SAR',
    vatRate: 0.15,
    vatNumber: '300056789100003',
    address: 'Olaya Street, Riyadh, KSA',
    phone: '+966-11-555-7890',
    email: 'info@najdvillage.com',
    subscriptionPlan: 'professional',
    isActive: true,
    createdAt: new Date('2023-06-10'),
    primaryColor: '#059669',
  },
  {
    id: 't4',
    name: 'Zuma Dubai',
    slug: 'zuma-dubai',
    countryCode: 'UAE',
    currency: 'AED',
    vatRate: 0.05,
    vatNumber: '100112233400003',
    address: 'Gate Village, DIFC, Dubai, UAE',
    phone: '+971-4-425-5660',
    email: 'info@zumadubai.com',
    subscriptionPlan: 'enterprise',
    isActive: true,
    createdAt: new Date('2022-11-01'),
    primaryColor: '#7c3aed',
  },
  {
    id: 't5',
    name: 'Spice Route',
    slug: 'spice-route',
    countryCode: 'KSA',
    currency: 'SAR',
    vatRate: 0.15,
    vatNumber: '300099887700003',
    address: 'Prince Sultan Rd, Jeddah, KSA',
    phone: '+966-12-333-4444',
    email: 'info@spiceroute.sa',
    subscriptionPlan: 'starter',
    isActive: false,
    createdAt: new Date('2024-01-05'),
    primaryColor: '#dc2626',
  },
  {
    id: 't6',
    name: 'Muscat Pearl',
    slug: 'muscat-pearl',
    countryCode: 'OMN',
    currency: 'OMR',
    vatRate: 0.05,
    vatNumber: 'OM100234567800001',
    address: 'Al Qurum, Muscat, Oman',
    phone: '+968-2456-7890',
    email: 'info@muscatpearl.om',
    subscriptionPlan: 'professional',
    isActive: true,
    createdAt: new Date('2024-03-01'),
    invoiceFooter: 'شكراً لزيارتكم | Thank you for visiting!',
    primaryColor: '#0891b2',
  },
  {
    id: 't7',
    name: 'Salalah Garden',
    slug: 'salalah-garden',
    countryCode: 'OMN',
    currency: 'OMR',
    vatRate: 0.05,
    vatNumber: 'OM100876543200001',
    address: 'Salalah, Dhofar, Oman',
    phone: '+968-2321-0987',
    email: 'hello@salalahgarden.om',
    subscriptionPlan: 'starter',
    isActive: true,
    createdAt: new Date('2024-05-10'),
    primaryColor: '#16a34a',
  },
]

export const MOCK_USERS: User[] = [
  { id: 'u0', tenantId: 't1', name: 'Platform Admin', email: 'admin@buysial.com', password: 'superadmin123', role: 'super_admin', language: 'en', isActive: true, hourlyRate: 0, createdAt: new Date('2022-01-01') },
  { id: 'u1', tenantId: 't1', name: 'Ahmed Al-Rashidi', email: 'ahmed@alfanar.com', password: 'admin123', role: 'admin', language: 'ar', isActive: true, hourlyRate: 0, createdAt: new Date('2023-01-15') },
  { id: 'u2', tenantId: 't1', name: 'Sarah Johnson', email: 'sarah@alfanar.com', password: 'manager123', role: 'manager', language: 'en', isActive: true, hourlyRate: 45, createdAt: new Date('2023-02-01') },
  { id: 'u3', tenantId: 't1', name: 'Mohammed Al-Otaibi', email: 'mo@alfanar.com', password: 'waiter123', role: 'waiter', language: 'ar', isActive: true, hourlyRate: 25, createdAt: new Date('2023-02-15') },
  { id: 'u4', tenantId: 't1', name: 'Fatima Hassan', email: 'fatima@alfanar.com', password: 'cashier123', role: 'cashier', language: 'ar', isActive: true, hourlyRate: 28, createdAt: new Date('2023-03-01') },
  { id: 'u5', tenantId: 't1', name: 'Carlos Rivera', email: 'carlos@alfanar.com', password: 'chef123', role: 'chef', language: 'en', isActive: true, hourlyRate: 55, createdAt: new Date('2023-01-20') },
  { id: 'u6', tenantId: 't2', name: 'Khalid Al-Mansoori', email: 'khalid@burjbites.ae', password: 'admin123', role: 'admin', language: 'ar', isActive: true, hourlyRate: 0, createdAt: new Date('2023-03-20') },
]

export const MOCK_CATEGORIES: Category[] = [
  { id: 'c1', tenantId: 't1', name: 'Starters', nameAr: 'المقبلات', icon: '🥗', sortOrder: 1, isActive: true },
  { id: 'c2', tenantId: 't1', name: 'Main Course', nameAr: 'الطبق الرئيسي', icon: '🍖', sortOrder: 2, isActive: true },
  { id: 'c3', tenantId: 't1', name: 'Grills', nameAr: 'المشويات', icon: '🔥', sortOrder: 3, isActive: true },
  { id: 'c4', tenantId: 't1', name: 'Seafood', nameAr: 'المأكولات البحرية', icon: '🦞', sortOrder: 4, isActive: true },
  { id: 'c5', tenantId: 't1', name: 'Desserts', nameAr: 'الحلويات', icon: '🍮', sortOrder: 5, isActive: true },
  { id: 'c6', tenantId: 't1', name: 'Beverages', nameAr: 'المشروبات', icon: '🧃', sortOrder: 6, isActive: true },
]

export const MOCK_MENU_ITEMS: MenuItem[] = [
  { id: 'm1', tenantId: 't1', categoryId: 'c1', name: 'Hummus Platter', nameAr: 'طبق الحمص', description: 'Creamy chickpea dip with olive oil and pita bread', price: 35, isAvailable: true, preparationTime: 5, calories: 320, isPopular: true, image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400' },
  { id: 'm2', tenantId: 't1', categoryId: 'c1', name: 'Fattoush Salad', nameAr: 'سلطة الفتوش', description: 'Fresh vegetables with toasted pita chips', price: 28, isAvailable: true, preparationTime: 8, calories: 180, image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400' },
  { id: 'm3', tenantId: 't1', categoryId: 'c2', name: 'Lamb Ouzi', nameAr: 'الأوزي', description: 'Slow-cooked whole lamb on bed of rice', price: 185, isAvailable: true, preparationTime: 25, calories: 850, isPopular: true, image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400' },
  { id: 'm4', tenantId: 't1', categoryId: 'c2', name: 'Chicken Mandi', nameAr: 'مندي الدجاج', description: 'Traditional slow-cooked chicken with spiced rice', price: 95, isAvailable: true, preparationTime: 20, calories: 650, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400' },
  { id: 'm5', tenantId: 't1', categoryId: 'c3', name: 'Mixed Grill', nameAr: 'مشكل مشويات', description: 'Assorted grilled meats with garlic sauce', price: 145, isAvailable: true, preparationTime: 20, calories: 780, isPopular: true, isNew: true, image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400' },
  { id: 'm6', tenantId: 't1', categoryId: 'c3', name: 'Lamb Chops', nameAr: 'ضلوع الخروف', description: 'Marinated lamb chops with herbs', price: 165, isAvailable: true, preparationTime: 18, calories: 720, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400' },
  { id: 'm7', tenantId: 't1', categoryId: 'c4', name: 'Grilled Hammour', nameAr: 'هامور مشوي', description: 'Fresh local fish with lemon butter sauce', price: 120, isAvailable: true, preparationTime: 15, calories: 420, image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400' },
  { id: 'm8', tenantId: 't1', categoryId: 'c5', name: 'Om Ali', nameAr: 'أم علي', description: 'Traditional bread pudding with nuts and cream', price: 35, isAvailable: true, preparationTime: 10, calories: 480, isPopular: true, image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400' },
  { id: 'm9', tenantId: 't1', categoryId: 'c5', name: 'Luqaimat', nameAr: 'لقيمات', description: 'Sweet dumplings with date syrup', price: 25, isAvailable: true, preparationTime: 8, calories: 380, image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400' },
  { id: 'm10', tenantId: 't1', categoryId: 'c6', name: 'Arabic Coffee', nameAr: 'قهوة عربية', description: 'Traditional cardamom-spiced coffee', price: 18, isAvailable: true, preparationTime: 3, calories: 15, image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400' },
  { id: 'm11', tenantId: 't1', categoryId: 'c6', name: 'Fresh Lemon Mint', nameAr: 'ليمون بالنعناع', description: 'Freshly squeezed lemon with mint leaves', price: 22, isAvailable: true, preparationTime: 3, calories: 85, isPopular: true, image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=400' },
]

export const MOCK_TABLES: Table[] = Array.from({ length: 20 }, (_, i) => ({
  id: `table-${i + 1}`,
  tenantId: 't1',
  number: i + 1,
  capacity: i % 4 === 0 ? 8 : i % 3 === 0 ? 6 : 4,
  isOccupied: [1, 3, 5, 7, 9, 12, 15].includes(i + 1),
  section: i < 8 ? 'Main Hall' : i < 14 ? 'Garden' : 'Private',
}))

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-001',
    tenantId: 't1',
    tableNumber: 1,
    waiterId: 'u3',
    items: [
      { id: 'oi1', menuItemId: 'm5', menuItem: MOCK_MENU_ITEMS[4], quantity: 2, unitPrice: 145, status: 'preparing' },
      { id: 'oi2', menuItemId: 'm10', menuItem: MOCK_MENU_ITEMS[9], quantity: 3, unitPrice: 18, status: 'ready' },
    ],
    status: 'preparing',
    subtotal: 344,
    vatRate: 0.15,
    vatAmount: 51.6,
    total: 395.6,
    isPaid: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000),
    invoiceNumber: 'INV-2024-0001',
  },
  {
    id: 'ord-002',
    tenantId: 't1',
    tableNumber: 3,
    waiterId: 'u3',
    items: [
      { id: 'oi3', menuItemId: 'm3', menuItem: MOCK_MENU_ITEMS[2], quantity: 1, unitPrice: 185, status: 'preparing' },
      { id: 'oi4', menuItemId: 'm1', menuItem: MOCK_MENU_ITEMS[0], quantity: 2, unitPrice: 35, status: 'ready' },
      { id: 'oi5', menuItemId: 'm8', menuItem: MOCK_MENU_ITEMS[7], quantity: 2, unitPrice: 35, status: 'pending' },
    ],
    status: 'preparing',
    subtotal: 325,
    vatRate: 0.15,
    vatAmount: 48.75,
    total: 373.75,
    isPaid: false,
    createdAt: new Date(Date.now() - 22 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000),
    invoiceNumber: 'INV-2024-0002',
  },
  {
    id: 'ord-003',
    tenantId: 't1',
    tableNumber: 5,
    waiterId: 'u3',
    items: [
      { id: 'oi6', menuItemId: 'm7', menuItem: MOCK_MENU_ITEMS[6], quantity: 2, unitPrice: 120, status: 'ready' },
      { id: 'oi7', menuItemId: 'm11', menuItem: MOCK_MENU_ITEMS[10], quantity: 4, unitPrice: 22, status: 'ready' },
    ],
    status: 'ready',
    subtotal: 328,
    vatRate: 0.15,
    vatAmount: 49.2,
    total: 377.2,
    isPaid: false,
    createdAt: new Date(Date.now() - 35 * 60 * 1000),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000),
    invoiceNumber: 'INV-2024-0003',
  },
]

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 'inv1', tenantId: 't1', name: 'Lamb (kg)', nameAr: 'لحم خروف', unit: 'kg', quantity: 45, minQuantity: 20, costPerUnit: 85, category: 'Meat', lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
  { id: 'inv2', tenantId: 't1', name: 'Chicken (kg)', nameAr: 'دجاج', unit: 'kg', quantity: 8, minQuantity: 15, costPerUnit: 32, category: 'Meat', lastRestocked: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) },
  { id: 'inv3', tenantId: 't1', name: 'Rice (kg)', nameAr: 'أرز', unit: 'kg', quantity: 120, minQuantity: 50, costPerUnit: 8, category: 'Dry Goods', lastRestocked: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
  { id: 'inv4', tenantId: 't1', name: 'Olive Oil (L)', nameAr: 'زيت زيتون', unit: 'L', quantity: 12, minQuantity: 10, costPerUnit: 45, category: 'Oils', lastRestocked: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
  { id: 'inv5', tenantId: 't1', name: 'Tomatoes (kg)', nameAr: 'طماطم', unit: 'kg', quantity: 3, minQuantity: 10, costPerUnit: 5, category: 'Vegetables', lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
  { id: 'inv6', tenantId: 't1', name: 'Cardamom (g)', nameAr: 'هيل', unit: 'g', quantity: 500, minQuantity: 200, costPerUnit: 0.15, category: 'Spices', lastRestocked: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) },
  { id: 'inv7', tenantId: 't1', name: 'Hammour Fish (kg)', nameAr: 'سمك هامور', unit: 'kg', quantity: 5, minQuantity: 8, costPerUnit: 95, category: 'Seafood', lastRestocked: new Date() },
]

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 's1', tenantId: 't1', name: 'Al-Watania Poultry', contact: 'Hassan Al-Watani', phone: '+966-11-444-5555', email: 'supply@alwatania.com', category: 'Poultry' },
  { id: 's2', tenantId: 't1', name: 'Saudi Seafood Co.', contact: 'Ali Al-Bahri', phone: '+966-12-777-8888', category: 'Seafood' },
  { id: 's3', tenantId: 't1', name: 'Green Valley Farms', contact: 'Samir Nasser', phone: '+966-11-222-3333', email: 'info@greenvalley.sa', category: 'Vegetables & Fruits' },
  { id: 's4', tenantId: 't1', name: 'Al-Marai Dairy', contact: 'Customer Service', phone: '+966-800-200-200', email: 'b2b@almarai.com', category: 'Dairy' },
]

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att1', tenantId: 't1', userId: 'u2', user: MOCK_USERS[1], clockIn: new Date(new Date().setHours(8, 0, 0)), date: new Date().toISOString().split('T')[0] },
  { id: 'att2', tenantId: 't1', userId: 'u3', user: MOCK_USERS[2], clockIn: new Date(new Date().setHours(9, 30, 0)), date: new Date().toISOString().split('T')[0] },
  { id: 'att3', tenantId: 't1', userId: 'u4', user: MOCK_USERS[3], clockIn: new Date(new Date().setHours(10, 0, 0)), date: new Date().toISOString().split('T')[0] },
  { id: 'att4', tenantId: 't1', userId: 'u5', user: MOCK_USERS[4], clockIn: new Date(new Date().setHours(7, 0, 0)), date: new Date().toISOString().split('T')[0] },
]

export const REVENUE_DATA = [
  { month: 'Jan', revenue: 125400, orders: 1240 },
  { month: 'Feb', revenue: 138200, orders: 1380 },
  { month: 'Mar', revenue: 142800, orders: 1420 },
  { month: 'Apr', revenue: 156900, orders: 1560 },
  { month: 'May', revenue: 168300, orders: 1670 },
  { month: 'Jun', revenue: 175200, orders: 1740 },
  { month: 'Jul', revenue: 189600, orders: 1880 },
  { month: 'Aug', revenue: 195400, orders: 1940 },
  { month: 'Sep', revenue: 183700, orders: 1820 },
  { month: 'Oct', revenue: 198200, orders: 1970 },
  { month: 'Nov', revenue: 210500, orders: 2090 },
  { month: 'Dec', revenue: 224800, orders: 2230 },
]

export const SUBSCRIPTION_GROWTH = [
  { month: 'Jan', starter: 12, professional: 8, enterprise: 3 },
  { month: 'Feb', starter: 15, professional: 11, enterprise: 4 },
  { month: 'Mar', starter: 18, professional: 14, enterprise: 5 },
  { month: 'Apr', starter: 20, professional: 17, enterprise: 6 },
  { month: 'May', starter: 22, professional: 21, enterprise: 7 },
  { month: 'Jun', starter: 25, professional: 24, enterprise: 8 },
]
